/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalForms;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class CloseTill extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrdersMenu
     */
    
    Color defaultColor, mouseEnteredColor;
    public CloseTill() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
                
        defaultColor = new Color(21,76,121);
        mouseEnteredColor = new Color(118,181,197);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_today_orders = new javax.swing.JPanel();
        label_today_orders = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(734, 609));

        panel_today_orders.setBackground(new java.awt.Color(21, 76, 121));
        panel_today_orders.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_today_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_today_ordersMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_today_ordersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_today_ordersMouseExited(evt);
            }
        });

        label_today_orders.setBackground(new java.awt.Color(255, 255, 255));
        label_today_orders.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_today_orders.setForeground(new java.awt.Color(255, 255, 255));
        label_today_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_today_orders.png"))); // NOI18N
        label_today_orders.setText(" Today Orders");
        label_today_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_today_ordersMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_today_ordersLayout = new javax.swing.GroupLayout(panel_today_orders);
        panel_today_orders.setLayout(panel_today_ordersLayout);
        panel_today_ordersLayout.setHorizontalGroup(
            panel_today_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_today_ordersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_today_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panel_today_ordersLayout.setVerticalGroup(
            panel_today_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_today_ordersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_today_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(panel_today_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(panel_today_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_today_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_today_ordersMousePressed

    private void label_today_ordersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_today_ordersMouseReleased

    private void label_today_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_today_ordersMouseClicked

    private void label_today_ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseExited
        // TODO add your handling code here:
        panel_today_orders.setBackground(defaultColor);
    }//GEN-LAST:event_label_today_ordersMouseExited

    private void label_today_ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseEntered
        // TODO add your handling code here:
        panel_today_orders.setBackground(mouseEnteredColor);
    }//GEN-LAST:event_label_today_ordersMouseEntered

    private void panel_today_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_today_ordersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_today_ordersMousePressed

    private void panel_today_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_today_ordersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_today_ordersMouseClicked

    private void panel_today_ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_today_ordersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_today_ordersMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_today_orders;
    private javax.swing.JPanel panel_today_orders;
    // End of variables declaration//GEN-END:variables
}
