/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalForms;

import Common.DBConnection;
import Forms.PrintFullReport;
import Model.OrdersReport;
import Model.SalesReport;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class TillClosing extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrdersMenu
     */
    
    Color defaultColor, mouseEnteredColor;
    PreparedStatement ps;
    Statement st;
    Connection con;
    ResultSet rs;
    OrdersReport ordersReport;
    SalesReport salesReport;
    
    
    
    public TillClosing() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
                
        defaultColor = new Color(21,76,121);
        mouseEnteredColor = new Color(118,181,197);
        
    }
    
     public void dbConnection() 
    {
        try {
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/pcHouse","root","hellmans");
              st = con.createStatement();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     public ArrayList<SalesReport> loadSalesList()
     {
        ArrayList<SalesReport> salesList = new ArrayList<>();
         
         try {
            // TODO add your handling code here:
            dbConnection();
            Date date = date_picker.getDate();
            String selectedDate = new SimpleDateFormat("dd/MM/yyyy").format(date);
            
            String querySale = "SELECT * FROM sales WHERE saleDate = ?";
            ps = con.prepareStatement(querySale);
            ps.setString(1, selectedDate);
            rs = ps.executeQuery();
            
            while (rs.next())
            {
                salesReport = new SalesReport(rs.getString("saleNo"), rs.getString("firstName"), rs.getString("lastName"),
                        rs.getString("productService"), rs.getDouble("total"), rs.getDouble("cash"), rs.getDouble("card"));
                
                salesList.add(salesReport);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TillClosing.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         return salesList;
     }
    
     public ArrayList<OrdersReport> loadOrdersList()
     {
        ArrayList<OrdersReport> ordersList = new ArrayList<>();
         
        try {
            dbConnection();
            Date date = date_picker.getDate();
            String selectedDate = new SimpleDateFormat("dd/MM/yyyy").format(date);
            
            String queryOrders = "SELECT * FROM completedOrders WHERE payDate = ?";
            ps = con.prepareStatement(queryOrders);
            ps.setString(1, selectedDate);
            rs = ps.executeQuery();
            
            while (rs.next())
            {
                /*
                    String _orderNo, String _firstName, String _lastName, String _productsService,
                String _deposit, String _due, double _cash, double _card) {
                */
                
               ordersReport = new OrdersReport(rs.getString("orderNo"), rs.getString("firstName"), rs.getString("lastName"),
                        rs.getString("productService"), rs.getString("deposit"), rs.getDouble("due"),rs.getDouble("cash"), rs.getDouble("card"));
               
               ordersList.add(ordersReport);
            }
            
                    
        } catch (SQLException ex) {
            Logger.getLogger(TillClosing.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return ordersList;
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_calendar = new javax.swing.JPanel();
        lbl_date = new javax.swing.JLabel();
        lbl_date_selected = new javax.swing.JLabel();
        date_picker = new com.toedter.calendar.JCalendar();
        btn_orders = new javax.swing.JButton();
        btn_full_report = new javax.swing.JButton();
        btn_sales = new javax.swing.JButton();

        setBorder(null);
        setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1049, 700));

        panel_calendar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_calendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_date.setText("dd/ mm /");
        panel_calendar.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lbl_date_selected.setText("Date Selected:");
        panel_calendar.add(lbl_date_selected, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        date_picker.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        date_picker.setDate(new java.util.Date(1629655133000L));
        date_picker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_pickerPropertyChange(evt);
            }
        });
        panel_calendar.add(date_picker, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 227));

        btn_orders.setBackground(new java.awt.Color(21, 76, 121));
        btn_orders.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_orders.setForeground(new java.awt.Color(255, 255, 255));
        btn_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_print.png"))); // NOI18N
        btn_orders.setText("Orders");
        btn_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordersActionPerformed(evt);
            }
        });

        btn_full_report.setBackground(new java.awt.Color(21, 76, 121));
        btn_full_report.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_full_report.setForeground(new java.awt.Color(255, 255, 255));
        btn_full_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_print.png"))); // NOI18N
        btn_full_report.setText("Print Full Report");
        btn_full_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_full_reportActionPerformed(evt);
            }
        });

        btn_sales.setBackground(new java.awt.Color(21, 76, 121));
        btn_sales.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_sales.setForeground(new java.awt.Color(255, 255, 255));
        btn_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_print.png"))); // NOI18N
        btn_sales.setText("Sales");
        btn_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_full_report, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(598, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_full_report, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordersActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_ordersActionPerformed

    private void btn_full_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_full_reportActionPerformed
        // TODO add your handling code here:
        ArrayList<SalesReport> listSales = loadSalesList();
        ArrayList<OrdersReport> listOrders = loadOrdersList();
        
        Date date = date_picker.getDate();
        String tillClosingDate = new SimpleDateFormat("dd/MM/yyyy").format(date);
            
        PrintFullReport printFullReport = new PrintFullReport(tillClosingDate, listSales, listOrders);
        printFullReport.setVisible(true);
    }//GEN-LAST:event_btn_full_reportActionPerformed

    private void btn_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salesActionPerformed

    private void date_pickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_pickerPropertyChange
        // TODO add your handling code here:
        if (date_picker.getDate() != null)
        {
            Date date = date_picker.getDate();
            String selectedDate = new SimpleDateFormat("dd / MM /").format(date);
            lbl_date.setText(selectedDate);
        }
    }//GEN-LAST:event_date_pickerPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_full_report;
    private javax.swing.JButton btn_orders;
    private javax.swing.JButton btn_sales;
    private com.toedter.calendar.JCalendar date_picker;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_date_selected;
    private javax.swing.JPanel panel_calendar;
    // End of variables declaration//GEN-END:variables
}
