/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pchouse;

import Forms.OrdersMenu;
import Forms.ProductsMenu;
import Forms.ReportsMenu;
import java.awt.Color;
import java.awt.Label;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    
    Color defaultColor, clickedColor;
    
    public MainMenu() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        //paOrders.setVisible(false);
        
        defaultColor = new Color(21,76,121);
        clickedColor = new Color(118,181,197);
        
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(defaultColor);
        
        label_orders.setBackground(defaultColor);
        label_products.setBackground(defaultColor);
        jLabel7.setBackground(defaultColor);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void setMouseEnteredColor(JLabel label)
    {
        label.setBackground(new Color(165,177,194));
        label.setOpaque(true);
    }
    
    public void setMouseExitedColor(JLabel label)
    {
        label.setBackground(new Color(75,101,132));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_menu_bar = new javax.swing.JPanel();
        panel_orders = new javax.swing.JPanel();
        label_orders = new javax.swing.JLabel();
        panel_products = new javax.swing.JPanel();
        label_products = new javax.swing.JLabel();
        panel_reports = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        desktop_panel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(21, 76, 121));
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(6, 57, 112));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/HermanCosta/Desktop/pcHouse/img/icons8-close-window-48.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panel_menu_bar.setBackground(new java.awt.Color(21, 76, 121));

        panel_orders.setBackground(new java.awt.Color(21, 76, 121));
        panel_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_ordersMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_ordersMouseClicked(evt);
            }
        });

        label_orders.setBackground(new java.awt.Color(255, 255, 255));
        label_orders.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_orders.setForeground(new java.awt.Color(255, 255, 255));
        label_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_orders.png"))); // NOI18N
        label_orders.setText(" Orders");
        label_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_ordersMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ordersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ordersLayout = new javax.swing.GroupLayout(panel_orders);
        panel_orders.setLayout(panel_ordersLayout);
        panel_ordersLayout.setHorizontalGroup(
            panel_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ordersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panel_ordersLayout.setVerticalGroup(
            panel_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ordersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_orders)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panel_products.setBackground(new java.awt.Color(21, 76, 121));
        panel_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_productsMousePressed(evt);
            }
        });

        label_products.setBackground(new java.awt.Color(255, 255, 255));
        label_products.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_products.setForeground(new java.awt.Color(255, 255, 255));
        label_products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_products.png"))); // NOI18N
        label_products.setText("Products");
        label_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_productsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_productsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_productsLayout = new javax.swing.GroupLayout(panel_products);
        panel_products.setLayout(panel_productsLayout);
        panel_productsLayout.setHorizontalGroup(
            panel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_products)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panel_productsLayout.setVerticalGroup(
            panel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_products, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_reports.setBackground(new java.awt.Color(21, 76, 121));
        panel_reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_reportsMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_reports.png"))); // NOI18N
        jLabel7.setText("Reports");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_reportsLayout = new javax.swing.GroupLayout(panel_reports);
        panel_reports.setLayout(panel_reportsLayout);
        panel_reportsLayout.setHorizontalGroup(
            panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reportsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_reportsLayout.setVerticalGroup(
            panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_reportsLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_menu_barLayout = new javax.swing.GroupLayout(panel_menu_bar);
        panel_menu_bar.setLayout(panel_menu_barLayout);
        panel_menu_barLayout.setHorizontalGroup(
            panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_orders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_barLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_products, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panel_menu_barLayout.setVerticalGroup(
            panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menu_barLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(panel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_reports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktop_panel.setBackground(new java.awt.Color(255, 255, 255));
        desktop_panel.setPreferredSize(new java.awt.Dimension(400, 400));
        desktop_panel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_menu_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_menu_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktop_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void label_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ordersMousePressed
        // TODO add your handling code here:
        panel_orders.setBackground(clickedColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(defaultColor);
    }//GEN-LAST:event_label_ordersMousePressed

    private void panel_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ordersMousePressed
        // TODO add your handling code here:
        panel_orders.setBackground(clickedColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(defaultColor);
    }//GEN-LAST:event_panel_ordersMousePressed

    private void label_productsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_productsMousePressed
        // TODO add your handling code here:
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(clickedColor);
        panel_reports.setBackground(defaultColor);
    }//GEN-LAST:event_label_productsMousePressed

    private void panel_productsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_productsMousePressed
        // TODO add your handling code here:
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(clickedColor);
        panel_reports.setBackground(defaultColor);
    }//GEN-LAST:event_panel_productsMousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(clickedColor);
    }//GEN-LAST:event_jLabel7MousePressed

    private void panel_reportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_reportsMousePressed
        // TODO add your handling code here:
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(clickedColor);
    }//GEN-LAST:event_panel_reportsMousePressed

    private void label_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ordersMouseClicked
        // TODO add your handling code here:
        OrdersMenu ordersMenu = new OrdersMenu();
        desktop_panel.removeAll();
        desktop_panel.add(ordersMenu).setVisible(true);
        
    }//GEN-LAST:event_label_ordersMouseClicked

    private void panel_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ordersMouseClicked
        // TODO add your handling code here:
        
                
        
    }//GEN-LAST:event_panel_ordersMouseClicked

    private void label_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_productsMouseClicked
        // TODO add your handling code here:
        ProductsMenu productsMenu = new ProductsMenu();
        desktop_panel.removeAll();
        desktop_panel.add(productsMenu).setVisible(true);
        
    }//GEN-LAST:event_label_productsMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        ReportsMenu reportsMenu = new ReportsMenu();
        desktop_panel.removeAll();
        desktop_panel.add(reportsMenu).setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label_orders;
    private javax.swing.JLabel label_products;
    private javax.swing.JPanel panel_menu_bar;
    private javax.swing.JPanel panel_orders;
    private javax.swing.JPanel panel_products;
    private javax.swing.JPanel panel_reports;
    // End of variables declaration//GEN-END:variables
}
