/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pchouse;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class PrintOrder extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public PrintOrder() {
        initComponents();
    }
    
    String _orderNo;
    String _customerName;
    String _contact;
    String _brand;
    String _model;
    String _serialNumber;
    String _fault;
    String _price;
    String _deposit;
    String _due;
    
    
    
    
    
    public PrintOrder(String orderNo, String customerName, String contact, String brand, String model, String serialNumber, String fault, String price, String deposit, String due) {
        
        initComponents();
        
        this._orderNo = orderNo;
        this._customerName = customerName;
        this._contact = contact;
        this._brand = brand;
        this._model = model;
        this._serialNumber = serialNumber;
        this._price = price;
        this._deposit = deposit;
        this._due = due;
        
        txPrintPanel.setText(txPrintPanel.getText() + "**********************************************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "******************PCHOUSE*********************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "\n");
        
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Order No: " + _orderNo +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Customer Name: " + _customerName +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Contact No: " + _contact +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Brand: " + _model +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "S/N: " + _serialNumber +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Price: €" + _deposit +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Deposit Paid: €" + _deposit +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Due: €" + _deposit +  "\n");
        
        txPrintPanel.setText(txPrintPanel.getText() + "**********************************************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "**********************************************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "********Thank you for choosing us*************\n");
        
        try {
            txPrintPanel.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PrintOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txPrintPanel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txPrintPanel.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jScrollPane1.setViewportView(txPrintPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txPrintPanel;
    // End of variables declaration//GEN-END:variables
}
