/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import InternalForms.NewOrder;
import InternalForms.OrderList;
import InternalForms.CloseTill;
import InternalForms.ProductsList;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class MainMenu extends javax.swing.JFrame {
    /**
     * Creates new form MainMenu
     */
    
    Color defaultColor, clickedColor;
    
    public MainMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        defaultColor = new Color(21,76,121);
        clickedColor = new Color(118,181,197);
        
        expandHome();
        //defaultColorToAll();
    }
    
    public void defaultColorToAll()
    {
        panel_home.setBackground(defaultColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(defaultColor);
        
        label_home.setBackground(defaultColor);
        label_products.setBackground(defaultColor);
        label_reports.setBackground(defaultColor);
    }
            
    public void expandHome()
    {
        panel_new_order.setVisible(false);
        panel_check_existing.setVisible(false);
        
        panel_add_new.setVisible(false);
        panel_sellings.setVisible(false);
        
        panel_today_orders.setVisible(false);
        panel_close_till.setVisible(false);
        
        //Set default color to outer labels
        panel_home.setBackground(clickedColor);
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(defaultColor);
    }
    

    public void expandOrders()
    {
        panel_check_existing.setVisible(true);
        panel_new_order.setVisible(true);
        
        //Set default color to the inner labels
        panel_check_existing.setBackground(defaultColor);
        panel_new_order.setBackground(defaultColor);
        
        //Set default color to the outer labels
        panel_home.setBackground(defaultColor);
        panel_orders.setBackground(clickedColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(defaultColor);
        
        //Colapse Products
        panel_add_new.setVisible(false);
        panel_sellings.setVisible(false);
        
        //Colapse Reports
        panel_today_orders.setVisible(false);
        panel_close_till.setVisible(false);
           
        
    }
    
    public void expandProducts()
    {
        panel_add_new.setVisible(true);
        panel_sellings.setVisible(true);
        
        //Set default color to the labels
        panel_add_new.setBackground(defaultColor);
        panel_sellings.setBackground(defaultColor);
        
        //Set default color to the outer labels
        panel_home.setBackground(defaultColor);
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(clickedColor);
        panel_reports.setBackground(defaultColor);
                
        //Colapse Orders
        panel_check_existing.setVisible(false);
        panel_new_order.setVisible(false);
        
        //Colapse Reports
        panel_today_orders.setVisible(false);
        panel_close_till.setVisible(false);
    }
    
    public void expandReports()
    {
        panel_today_orders.setVisible(true);
        panel_close_till.setVisible(true);
        
        //Set default color to the labels
        panel_today_orders.setBackground(defaultColor);
        panel_close_till.setBackground(defaultColor);
        
        //Set default color to the outer labels
        panel_home.setBackground(defaultColor);
        panel_orders.setBackground(defaultColor);
        panel_products.setBackground(defaultColor);
        panel_reports.setBackground(clickedColor);
      
           
        //Colapse Products
        panel_check_existing.setVisible(false);
        panel_new_order.setVisible(false);
        
        //Colapse Orders
        panel_add_new.setVisible(false);
        panel_sellings.setVisible(false);
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void setMouseEnteredColor(JLabel label)
    {
        label.setBackground(new Color(165,177,194));
        label.setOpaque(true);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_window = new javax.swing.JPanel();
        panel_header = new javax.swing.JPanel();
        panel_menu_bar = new javax.swing.JPanel();
        panel_home = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        panel_products = new javax.swing.JPanel();
        label_products = new javax.swing.JLabel();
        panel_reports = new javax.swing.JPanel();
        label_reports = new javax.swing.JLabel();
        panel_check_existing = new javax.swing.JPanel();
        label_check_existing = new javax.swing.JLabel();
        panel_new_order = new javax.swing.JPanel();
        label_new_order = new javax.swing.JLabel();
        panel_add_new = new javax.swing.JPanel();
        label_products_list = new javax.swing.JLabel();
        panel_sellings = new javax.swing.JPanel();
        label_sellings = new javax.swing.JLabel();
        panel_close_till = new javax.swing.JPanel();
        label_close_till = new javax.swing.JLabel();
        panel_today_orders = new javax.swing.JPanel();
        label_today_orders = new javax.swing.JLabel();
        panel_orders = new javax.swing.JPanel();
        label_orders = new javax.swing.JLabel();
        desktop_panel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(21, 76, 121));

        panel_header.setBackground(new java.awt.Color(6, 57, 112));

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panel_menu_bar.setBackground(new java.awt.Color(21, 76, 121));

        panel_home.setBackground(new java.awt.Color(21, 76, 121));
        panel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_homeMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_homeMouseClicked(evt);
            }
        });

        label_home.setBackground(new java.awt.Color(255, 255, 255));
        label_home.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_home.setForeground(new java.awt.Color(255, 255, 255));
        label_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_home.png"))); // NOI18N
        label_home.setText(" Home");
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_homeMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_home))
        );

        panel_products.setBackground(new java.awt.Color(21, 76, 121));
        panel_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_productsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_productsMouseClicked(evt);
            }
        });

        label_products.setBackground(new java.awt.Color(255, 255, 255));
        label_products.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_products.setForeground(new java.awt.Color(255, 255, 255));
        label_products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_products.png"))); // NOI18N
        label_products.setText(" Products");
        label_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_productsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_productsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_productsLayout = new javax.swing.GroupLayout(panel_products);
        panel_products.setLayout(panel_productsLayout);
        panel_productsLayout.setHorizontalGroup(
            panel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panel_productsLayout.setVerticalGroup(
            panel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_productsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(label_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_reports.setBackground(new java.awt.Color(21, 76, 121));
        panel_reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_reportsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_reportsMouseClicked(evt);
            }
        });

        label_reports.setBackground(new java.awt.Color(255, 255, 255));
        label_reports.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_reports.setForeground(new java.awt.Color(255, 255, 255));
        label_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_reports.png"))); // NOI18N
        label_reports.setText(" Reports");
        label_reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_reportsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_reportsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_reportsLayout = new javax.swing.GroupLayout(panel_reports);
        panel_reports.setLayout(panel_reportsLayout);
        panel_reportsLayout.setHorizontalGroup(
            panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_reportsLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(label_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_reportsLayout.setVerticalGroup(
            panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reportsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(label_reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_check_existing.setBackground(new java.awt.Color(21, 76, 121));
        panel_check_existing.setPreferredSize(new java.awt.Dimension(160, 32));
        panel_check_existing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_check_existingMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_check_existingMouseClicked(evt);
            }
        });

        label_check_existing.setBackground(new java.awt.Color(255, 255, 255));
        label_check_existing.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_check_existing.setForeground(new java.awt.Color(255, 255, 255));
        label_check_existing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_check_existing.png"))); // NOI18N
        label_check_existing.setText("Check Existing");
        label_check_existing.setToolTipText("");
        label_check_existing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_check_existingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_check_existingMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_check_existingMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_check_existingMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_check_existingMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_check_existingLayout = new javax.swing.GroupLayout(panel_check_existing);
        panel_check_existing.setLayout(panel_check_existingLayout);
        panel_check_existingLayout.setHorizontalGroup(
            panel_check_existingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_check_existing, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        panel_check_existingLayout.setVerticalGroup(
            panel_check_existingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_check_existing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_new_order.setBackground(new java.awt.Color(21, 76, 121));
        panel_new_order.setPreferredSize(new java.awt.Dimension(160, 32));
        panel_new_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_new_orderMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_new_orderMouseClicked(evt);
            }
        });

        label_new_order.setBackground(new java.awt.Color(255, 255, 255));
        label_new_order.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_new_order.setForeground(new java.awt.Color(255, 255, 255));
        label_new_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_new_order.png"))); // NOI18N
        label_new_order.setText("New Order");
        label_new_order.setToolTipText("");
        label_new_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_new_orderMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_new_orderMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_new_orderMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_new_orderMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_new_orderLayout = new javax.swing.GroupLayout(panel_new_order);
        panel_new_order.setLayout(panel_new_orderLayout);
        panel_new_orderLayout.setHorizontalGroup(
            panel_new_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_new_orderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_new_order, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_new_orderLayout.setVerticalGroup(
            panel_new_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_new_order, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_add_new.setBackground(new java.awt.Color(21, 76, 121));
        panel_add_new.setPreferredSize(new java.awt.Dimension(160, 32));
        panel_add_new.setRequestFocusEnabled(false);
        panel_add_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_add_newMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_add_newMouseClicked(evt);
            }
        });

        label_products_list.setBackground(new java.awt.Color(255, 255, 255));
        label_products_list.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_products_list.setForeground(new java.awt.Color(255, 255, 255));
        label_products_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_product_list.png"))); // NOI18N
        label_products_list.setText("Products List");
        label_products_list.setPreferredSize(new java.awt.Dimension(168, 32));
        label_products_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_products_listMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_products_listMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_products_listMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_products_listMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_add_newLayout = new javax.swing.GroupLayout(panel_add_new);
        panel_add_new.setLayout(panel_add_newLayout);
        panel_add_newLayout.setHorizontalGroup(
            panel_add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_newLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_products_list, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        panel_add_newLayout.setVerticalGroup(
            panel_add_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_products_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_sellings.setBackground(new java.awt.Color(21, 76, 121));
        panel_sellings.setPreferredSize(new java.awt.Dimension(160, 32));
        panel_sellings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_sellingsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_sellingsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_sellingsMouseExited(evt);
            }
        });

        label_sellings.setBackground(new java.awt.Color(255, 255, 255));
        label_sellings.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_sellings.setForeground(new java.awt.Color(255, 255, 255));
        label_sellings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_sellings.png"))); // NOI18N
        label_sellings.setText("Sellings");
        label_sellings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_sellingsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_sellingsMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_sellingsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_sellingsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_sellingsMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_sellingsLayout = new javax.swing.GroupLayout(panel_sellings);
        panel_sellings.setLayout(panel_sellingsLayout);
        panel_sellingsLayout.setHorizontalGroup(
            panel_sellingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sellingsLayout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(label_sellings, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_sellingsLayout.setVerticalGroup(
            panel_sellingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_sellings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_close_till.setBackground(new java.awt.Color(21, 76, 121));
        panel_close_till.setPreferredSize(new java.awt.Dimension(160, 32));
        panel_close_till.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_close_tillMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_close_tillMouseClicked(evt);
            }
        });

        label_close_till.setBackground(new java.awt.Color(255, 255, 255));
        label_close_till.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_close_till.setForeground(new java.awt.Color(255, 255, 255));
        label_close_till.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_close_till.png"))); // NOI18N
        label_close_till.setText(" Close Till");
        label_close_till.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_close_tillMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_close_tillMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_close_tillMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_close_tillMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_close_tillLayout = new javax.swing.GroupLayout(panel_close_till);
        panel_close_till.setLayout(panel_close_tillLayout);
        panel_close_tillLayout.setHorizontalGroup(
            panel_close_tillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_close_tillLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(label_close_till, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_close_tillLayout.setVerticalGroup(
            panel_close_tillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_close_till, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_today_orders.setBackground(new java.awt.Color(21, 76, 121));
        panel_today_orders.setPreferredSize(new java.awt.Dimension(233, 32));
        panel_today_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_today_ordersMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_today_ordersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_today_ordersMouseExited(evt);
            }
        });

        label_today_orders.setBackground(new java.awt.Color(255, 255, 255));
        label_today_orders.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        label_today_orders.setForeground(new java.awt.Color(255, 255, 255));
        label_today_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_today_orders.png"))); // NOI18N
        label_today_orders.setText(" Today Orders");
        label_today_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_today_ordersMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_today_ordersMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panel_today_ordersLayout = new javax.swing.GroupLayout(panel_today_orders);
        panel_today_orders.setLayout(panel_today_ordersLayout);
        panel_today_ordersLayout.setHorizontalGroup(
            panel_today_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_today_ordersLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(label_today_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_today_ordersLayout.setVerticalGroup(
            panel_today_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_today_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_orders.setBackground(new java.awt.Color(21, 76, 121));
        panel_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_ordersMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_ordersMouseClicked(evt);
            }
        });

        label_orders.setBackground(new java.awt.Color(255, 255, 255));
        label_orders.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_orders.setForeground(new java.awt.Color(255, 255, 255));
        label_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_orders.png"))); // NOI18N
        label_orders.setText(" Orders");
        label_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_ordersMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ordersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ordersLayout = new javax.swing.GroupLayout(panel_orders);
        panel_orders.setLayout(panel_ordersLayout);
        panel_ordersLayout.setHorizontalGroup(
            panel_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ordersLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panel_ordersLayout.setVerticalGroup(
            panel_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_menu_barLayout = new javax.swing.GroupLayout(panel_menu_bar);
        panel_menu_bar.setLayout(panel_menu_barLayout);
        panel_menu_barLayout.setHorizontalGroup(
            panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_barLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel_sellings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_add_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panel_new_order, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel_check_existing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(panel_today_orders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_close_till, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panel_menu_barLayout.setVerticalGroup(
            panel_menu_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menu_barLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_check_existing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_new_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_add_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_sellings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_reports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_today_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_close_till, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        desktop_panel.setBackground(new java.awt.Color(255, 255, 255));
        desktop_panel.setMaximumSize(new java.awt.Dimension(1049, 827));
        desktop_panel.setSize(new java.awt.Dimension(1049, 827));
        desktop_panel.setLayout(null);

        javax.swing.GroupLayout panel_windowLayout = new javax.swing.GroupLayout(panel_window);
        panel_window.setLayout(panel_windowLayout);
        panel_windowLayout.setHorizontalGroup(
            panel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_windowLayout.createSequentialGroup()
                .addGroup(panel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_windowLayout.createSequentialGroup()
                        .addComponent(panel_menu_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(desktop_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_windowLayout.setVerticalGroup(
            panel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_windowLayout.createSequentialGroup()
                .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktop_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_menu_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_label_homeMousePressed

    private void panel_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMousePressed
 
    }//GEN-LAST:event_panel_homeMousePressed

    private void label_productsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_productsMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_label_productsMousePressed

    private void panel_productsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_productsMousePressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_panel_productsMousePressed

    private void label_reportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reportsMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_label_reportsMousePressed

    private void panel_reportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_reportsMousePressed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_panel_reportsMousePressed

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        // TODO add your handling code here:
       expandHome();
       new MainMenu().setVisible(true);
    }//GEN-LAST:event_label_homeMouseClicked

    private void panel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panel_homeMouseClicked

    private void label_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_productsMouseClicked
        // TODO add your handling code here:
        expandProducts();
    }//GEN-LAST:event_label_productsMouseClicked

    private void label_reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reportsMouseClicked
        // TODO add your handling code here:
        expandReports();
    }//GEN-LAST:event_label_reportsMouseClicked

    private void panel_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_productsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panel_productsMouseClicked

    private void panel_reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_reportsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_reportsMouseClicked

    private void label_check_existingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_check_existingMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_check_existingMousePressed

    private void label_check_existingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_check_existingMouseClicked
        // TODO add your handling code here:
        OrderList ordersMenu = new OrderList();
        desktop_panel.removeAll();
        desktop_panel.add(ordersMenu).setVisible(true);
        
        panel_check_existing.setBackground(clickedColor);
        panel_new_order.setBackground(defaultColor);
    }//GEN-LAST:event_label_check_existingMouseClicked

    private void label_check_existingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_check_existingMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_check_existingMouseExited

    private void label_check_existingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_check_existingMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_check_existingMouseEntered

    private void panel_check_existingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_check_existingMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_check_existingMousePressed

    private void panel_check_existingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_check_existingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_check_existingMouseClicked

    private void label_new_orderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_new_orderMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_new_orderMousePressed

    private void label_new_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_new_orderMouseClicked
        // TODO add your handling code here:
        NewOrder newOrder = new NewOrder();
        desktop_panel.removeAll();
        desktop_panel.add(newOrder).setVisible(true);
        
        panel_check_existing.setBackground(defaultColor);
        panel_new_order.setBackground(clickedColor);
    }//GEN-LAST:event_label_new_orderMouseClicked

    private void label_new_orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_new_orderMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_new_orderMouseExited

    private void label_new_orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_new_orderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_new_orderMouseEntered

    private void panel_new_orderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_new_orderMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_new_orderMousePressed

    private void panel_new_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_new_orderMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panel_new_orderMouseClicked

    private void label_products_listMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_products_listMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_products_listMousePressed

    private void label_products_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_products_listMouseClicked
        // TODO add your handling code here:
        //Open ProductsLis Class
        ProductsList productsList = new ProductsList();
        desktop_panel.removeAll();
        desktop_panel.add(productsList).setVisible(true);
        
        panel_add_new.setBackground(clickedColor);
        panel_sellings.setBackground(defaultColor);
    }//GEN-LAST:event_label_products_listMouseClicked

    private void label_products_listMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_products_listMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_products_listMouseExited

    private void label_products_listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_products_listMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_products_listMouseEntered

    private void panel_add_newMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_add_newMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_add_newMousePressed

    private void panel_add_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_add_newMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_add_newMouseClicked

    private void label_sellingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_sellingsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_sellingsMousePressed

    private void label_sellingsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_sellingsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_sellingsMouseReleased

    private void label_sellingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_sellingsMouseClicked
        // TODO add your handling code here:
        panel_add_new.setBackground(defaultColor);
        panel_sellings.setBackground(clickedColor);
    }//GEN-LAST:event_label_sellingsMouseClicked

    private void label_sellingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_sellingsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_sellingsMouseExited

    private void label_sellingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_sellingsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_sellingsMouseEntered

    private void panel_sellingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sellingsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_sellingsMousePressed

    private void panel_sellingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sellingsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_sellingsMouseClicked

    private void panel_sellingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sellingsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_sellingsMouseExited

    private void label_close_tillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_close_tillMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_close_tillMousePressed

    private void label_close_tillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_close_tillMouseClicked
        // TODO add your handling code here:
        panel_today_orders.setBackground(defaultColor);
        panel_close_till.setBackground(clickedColor);
    }//GEN-LAST:event_label_close_tillMouseClicked

    private void label_close_tillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_close_tillMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_close_tillMouseExited

    private void label_close_tillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_close_tillMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_close_tillMouseEntered

    private void panel_close_tillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_close_tillMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_close_tillMousePressed

    private void panel_close_tillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_close_tillMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panel_close_tillMouseClicked

    private void label_today_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_today_ordersMousePressed

    private void label_today_ordersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_today_ordersMouseReleased

    private void label_today_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseClicked
        // TODO add your handling code here:
        CloseTill closeTill = new CloseTill();
        desktop_panel.removeAll();
        desktop_panel.add(closeTill).setVisible(true);
        
        panel_today_orders.setBackground(clickedColor);
        panel_close_till.setBackground(defaultColor);
    }//GEN-LAST:event_label_today_ordersMouseClicked

    private void label_today_ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_today_ordersMouseExited

    private void label_today_ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_today_ordersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_today_ordersMouseEntered

    private void panel_today_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_today_ordersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_today_ordersMousePressed

    private void panel_today_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_today_ordersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_today_ordersMouseClicked

    private void panel_today_ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_today_ordersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_today_ordersMouseExited

    private void label_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ordersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ordersMousePressed

    private void label_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ordersMouseClicked
        // TODO add your handling code here:
        expandOrders();
    }//GEN-LAST:event_label_ordersMouseClicked

    private void panel_ordersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ordersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_ordersMousePressed

    private void panel_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ordersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_ordersMouseClicked

    private void label_check_existingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_check_existingMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_label_check_existingMouseReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop_panel;
    private javax.swing.JLabel label_check_existing;
    private javax.swing.JLabel label_close_till;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_new_order;
    private javax.swing.JLabel label_orders;
    private javax.swing.JLabel label_products;
    private javax.swing.JLabel label_products_list;
    private javax.swing.JLabel label_reports;
    private javax.swing.JLabel label_sellings;
    private javax.swing.JLabel label_today_orders;
    private javax.swing.JPanel panel_add_new;
    private javax.swing.JPanel panel_check_existing;
    private javax.swing.JPanel panel_close_till;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_menu_bar;
    private javax.swing.JPanel panel_new_order;
    private javax.swing.JPanel panel_orders;
    private javax.swing.JPanel panel_products;
    private javax.swing.JPanel panel_reports;
    private javax.swing.JPanel panel_sellings;
    private javax.swing.JPanel panel_today_orders;
    private javax.swing.JPanel panel_window;
    // End of variables declaration//GEN-END:variables
}
