/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import javax.swing.JOptionPane;

/**
 *
 * @author HermanCosta
 */
public class MoneyCounter extends javax.swing.JFrame {

    String tillClosingDate;
//    double fiveHundred = 500, twoHundred = 200, oneHundred = 100, fifty = 50, twenty = 20, ten = 10, five = 5;
//    double twoEuro = 2, oneEuro = 1, fiftyCents = 0.5 , twentyCents = 0.2, tenCents = 0.1, 
//            fiveCents = 0.05, twoCents = 0.02, oneCent = 0.01, totalMoney = 0; 
    double totalMoney = 0; 
    int input500Qty, input200Qty, input100Qty, input50Qty, input20Qty, input10Qty, input5Qty; 
    int input2Qty, input1Qty, input50cQty, input20cQty, input10cQty, input5cQty, input2cQty, input1cQty; 
    
    public MoneyCounter() {
        initComponents();
    }

    public void calcMoneyCounter()
    {
        double total500 = 500 * input500Qty;
        double total200 = 200 * input200Qty;
        double total100 = 100 * input100Qty;
        double total50 = 50 * input50Qty;
        double total20 = 20 * input20Qty;
        double total10 = 10 * input10Qty;
        double total5 = 5 * input5Qty;
         
        double total2 = 2 * input2Qty;
        double total1 = 1 * input1Qty;
        double total50c = 0.5 * input50cQty;
        double total20c = 0.2 * input20cQty;
        double total10c = 0.1 * input10cQty; 
        double total5c = 0.05 * input5cQty;
        double total2c = 0.02 * input2cQty;
        double total1c = 0.01 * input1cQty;
        
        totalMoney = total500 + total200 + total100 + total50 + total20 + total10 + total5
                + total2 + total1 + total50c + + total20c + total10c + total5c
                + total2c + total1c;
        
        totalMoney = Math.round(totalMoney * 100d) / 100d;
        txt_total_money.setText(String.valueOf(totalMoney));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bank_notes = new javax.swing.JPanel();
        lbl_€500 = new javax.swing.JLabel();
        txt_500 = new javax.swing.JTextField();
        lbl_€200 = new javax.swing.JLabel();
        txt_200 = new javax.swing.JTextField();
        lbl_€100 = new javax.swing.JLabel();
        txt_100 = new javax.swing.JTextField();
        lbl_€50 = new javax.swing.JLabel();
        txt_50 = new javax.swing.JTextField();
        lbl_€20 = new javax.swing.JLabel();
        txt_20 = new javax.swing.JTextField();
        lbl_€10 = new javax.swing.JLabel();
        txt_10 = new javax.swing.JTextField();
        lbl_€5 = new javax.swing.JLabel();
        txt_5 = new javax.swing.JTextField();
        lbl_euro_money_counter = new javax.swing.JLabel();
        panel_coins = new javax.swing.JPanel();
        lbl_2 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JTextField();
        lbl_1 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        lbl_50c = new javax.swing.JLabel();
        txt_50c = new javax.swing.JTextField();
        lbl_20c = new javax.swing.JLabel();
        txt_20c = new javax.swing.JTextField();
        lbl_10c = new javax.swing.JLabel();
        txt_10c = new javax.swing.JTextField();
        lbl_5c = new javax.swing.JLabel();
        txt_5c = new javax.swing.JTextField();
        lbl_2c = new javax.swing.JLabel();
        txt_2c = new javax.swing.JTextField();
        lbl_1c = new javax.swing.JLabel();
        txt_1c = new javax.swing.JTextField();
        txt_total_money = new javax.swing.JTextField();
        lbl_total_money = new javax.swing.JLabel();
        lbl_bank_notes = new javax.swing.JLabel();
        txt_bank_notes = new javax.swing.JTextField();
        lbl_coins = new javax.swing.JLabel();
        txt_coins = new javax.swing.JTextField();
        btn_copy = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_bank_notes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank Notes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 14))); // NOI18N

        lbl_€500.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_€500.setText("€500");

        txt_500.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_500KeyReleased(evt);
            }
        });

        lbl_€200.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_€200.setText("€200");

        txt_200.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_200ActionPerformed(evt);
            }
        });
        txt_200.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_200KeyReleased(evt);
            }
        });

        lbl_€100.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_€100.setText("€100");

        txt_100.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_100KeyReleased(evt);
            }
        });

        lbl_€50.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_€50.setText("€50");

        txt_50.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_50KeyReleased(evt);
            }
        });

        lbl_€20.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_€20.setText("€20");

        txt_20.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_20KeyReleased(evt);
            }
        });

        lbl_€10.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_€10.setText("€10");

        txt_10.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_10KeyReleased(evt);
            }
        });

        lbl_€5.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_€5.setText("€5");

        txt_5.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_bank_notesLayout = new javax.swing.GroupLayout(panel_bank_notes);
        panel_bank_notes.setLayout(panel_bank_notesLayout);
        panel_bank_notesLayout.setHorizontalGroup(
            panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_500, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_€500)))
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_200, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_€200)))
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_100, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbl_€100)))
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbl_€50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_€20))
                    .addComponent(txt_20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_€10))
                    .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bank_notesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_€5)
                        .addGap(32, 32, 32))))
        );
        panel_bank_notesLayout.setVerticalGroup(
            panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_€10)
                            .addComponent(lbl_€5))
                        .addGap(0, 0, 0)
                        .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addComponent(lbl_€20)
                        .addGap(0, 0, 0)
                        .addComponent(txt_20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_100, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_200, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_€500)
                            .addComponent(lbl_€200)
                            .addComponent(lbl_€100)
                            .addComponent(lbl_€50))
                        .addGap(0, 0, 0)
                        .addComponent(txt_500, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_euro_money_counter.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        lbl_euro_money_counter.setText("EURO Money Counter");

        panel_coins.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coins", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 14))); // NOI18N

        lbl_2.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_2.setText("€2");

        txt_2.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_2KeyReleased(evt);
            }
        });

        lbl_1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_1.setText("€1");

        txt_1.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_1KeyReleased(evt);
            }
        });

        lbl_50c.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_50c.setText("50c");

        txt_50c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_50c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_50cKeyReleased(evt);
            }
        });

        lbl_20c.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_20c.setText("20c");

        txt_20c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_20c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_20cActionPerformed(evt);
            }
        });
        txt_20c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_20cKeyReleased(evt);
            }
        });

        lbl_10c.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_10c.setText("10c");

        txt_10c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_10c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_10cKeyReleased(evt);
            }
        });

        lbl_5c.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_5c.setText("5c");

        txt_5c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_5c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_5cKeyReleased(evt);
            }
        });

        lbl_2c.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_2c.setText("2c");

        txt_2c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_2c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_2cKeyReleased(evt);
            }
        });

        lbl_1c.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_1c.setText("1c");

        txt_1c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_1c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_1cKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_coinsLayout = new javax.swing.GroupLayout(panel_coins);
        panel_coins.setLayout(panel_coinsLayout);
        panel_coinsLayout.setHorizontalGroup(
            panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_coinsLayout.createSequentialGroup()
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_2)))
                .addGap(18, 18, 18)
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                        .addComponent(lbl_1)
                        .addGap(37, 37, 37)))
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_50c))
                    .addComponent(txt_50c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addComponent(txt_20c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                        .addComponent(lbl_20c)
                        .addGap(29, 29, 29)))
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_10c))
                    .addComponent(txt_10c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_5c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_5c)))
                .addGap(18, 18, 18)
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_2c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                        .addComponent(lbl_2c)
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addComponent(txt_1c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                        .addComponent(lbl_1c)
                        .addGap(28, 28, 28))))
        );
        panel_coinsLayout.setVerticalGroup(
            panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_coinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_1c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_1c)
                            .addComponent(lbl_2c))
                        .addGap(30, 30, 30))
                    .addComponent(txt_2c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_5c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_10c)
                            .addComponent(lbl_20c)
                            .addComponent(lbl_5c))
                        .addGap(0, 0, 0)
                        .addComponent(txt_10c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_20c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_50c)
                            .addComponent(lbl_1))
                        .addGap(0, 0, 0)
                        .addComponent(txt_50c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addComponent(lbl_2)
                        .addGap(0, 0, 0)
                        .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_total_money.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N

        lbl_total_money.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_total_money.setText("Total Money €");

        lbl_bank_notes.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_bank_notes.setText("Bank notes");

        txt_bank_notes.setEditable(false);
        txt_bank_notes.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_bank_notes.setFocusable(false);
        txt_bank_notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bank_notesActionPerformed(evt);
            }
        });

        lbl_coins.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_coins.setText("Coins");

        txt_coins.setEditable(false);
        txt_coins.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_coins.setFocusable(false);
        txt_coins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coinsActionPerformed(evt);
            }
        });

        btn_copy.setBackground(new java.awt.Color(0, 0, 0));
        btn_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_copy.png"))); // NOI18N
        btn_copy.setToolTipText("Copy to total money to clipboard");
        btn_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copyActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 0, 0));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_erase.png"))); // NOI18N
        btn_clear.setToolTipText("Clear fields");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_coins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_total_money)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_money, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_bank_notes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bank_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_coins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_coins, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel_bank_notes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_euro_money_counter)
                        .addGap(238, 238, 238))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbl_euro_money_counter)
                .addGap(18, 18, 18)
                .addComponent(panel_bank_notes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_coins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_total_money, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_total_money)
                        .addComponent(txt_bank_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_bank_notes)
                        .addComponent(txt_coins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_coins))
                    .addComponent(btn_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_200ActionPerformed

    private void txt_coinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coinsActionPerformed

    private void btn_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copyActionPerformed
        // TODO add your handling code here:
        StringSelection stringSelection = new StringSelection(txt_total_money.getText());
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection , null);
        JOptionPane.showMessageDialog(this, txt_total_money.getText() + " Copied to Clipboard");
    }//GEN-LAST:event_btn_copyActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_bank_notesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bank_notesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bank_notesActionPerformed

    private void txt_500KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_500KeyReleased
        // TODO add your handling code here:
        if (txt_500.getText().trim().isEmpty()) {
            input500Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input500Qty = Integer.parseInt(txt_500.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_500KeyReleased

    private void txt_200KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_200KeyReleased
        // TODO add your handling code here:
        if (txt_200.getText().trim().isEmpty()) {
            input200Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input200Qty = Integer.parseInt(txt_200.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_200KeyReleased

    private void txt_100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_100KeyReleased
        // TODO add your handling code here:
        if (txt_100.getText().trim().isEmpty()) {
            input100Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input100Qty = Integer.parseInt(txt_100.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_100KeyReleased

    private void txt_50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_50KeyReleased
        // TODO add your handling code here:
        if (txt_50.getText().trim().isEmpty()) {
            input50Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input50Qty = Integer.parseInt(txt_50.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_50KeyReleased

    private void txt_20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_20KeyReleased
        // TODO add your handling code here:
        if (txt_20.getText().trim().isEmpty()) {
            input20Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input20Qty = Integer.parseInt(txt_20.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_20KeyReleased

    private void txt_10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_10KeyReleased
        // TODO add your handling code here:
        if (txt_10.getText().trim().isEmpty()) {
            input10Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input10Qty = Integer.parseInt(txt_10.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_10KeyReleased

    private void txt_5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_5KeyReleased
        // TODO add your handling code here:
        if (txt_5.getText().trim().isEmpty()) {
            input5Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input5Qty = Integer.parseInt(txt_5.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_5KeyReleased

    private void txt_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2KeyReleased
        // TODO add your handling code here:
        if (txt_2.getText().trim().isEmpty()) {
            input2Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input2Qty = Integer.parseInt(txt_2.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_2KeyReleased

    private void txt_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1KeyReleased
        // TODO add your handling code here:
        if (txt_1.getText().trim().isEmpty()) {
            input1Qty = 0;
            calcMoneyCounter();
        }
        else
        {
            input1Qty = Integer.parseInt(txt_1.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_1KeyReleased

    private void txt_50cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_50cKeyReleased
        // TODO add your handling code here:
        if (txt_50c.getText().trim().isEmpty()) {
            input50cQty = 0;
            calcMoneyCounter();
        }
        else
        {
            input50cQty = Integer.parseInt(txt_50c.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_50cKeyReleased

    private void txt_20cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_20cKeyReleased
        // TODO add your handling code here:
         if (txt_20c.getText().trim().isEmpty()) {
            input20cQty = 0;
            calcMoneyCounter();
        }
        else
        {
            input20cQty = Integer.parseInt(txt_20c.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_20cKeyReleased

    private void txt_10cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_10cKeyReleased
        // TODO add your handling code here:
         if (txt_10c.getText().trim().isEmpty()) {
            input10cQty = 0;
            calcMoneyCounter();
        }
        else
        {
            input10cQty = Integer.parseInt(txt_10c.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_10cKeyReleased

    private void txt_5cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_5cKeyReleased
        // TODO add your handling code here:
         if (txt_5c.getText().trim().isEmpty()) {
            input5cQty = 0;
            calcMoneyCounter();
        }
        else
        {
            input5cQty = Integer.parseInt(txt_5c.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_5cKeyReleased

    private void txt_2cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2cKeyReleased
        // TODO add your handling code here:
         if (txt_2c.getText().trim().isEmpty()) {
            input2cQty = 0;
            calcMoneyCounter();
        }
        else
        {
            input2cQty = Integer.parseInt(txt_2c.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_2cKeyReleased

    private void txt_1cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1cKeyReleased
        // TODO add your handling code here:
         if (txt_1c.getText().trim().isEmpty()) {
            input1cQty = 0;
            calcMoneyCounter();
        }
        else
        {
            input1cQty = Integer.parseInt(txt_1c.getText());
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_1cKeyReleased

    private void txt_20cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_20cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_20cActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_copy;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_10c;
    private javax.swing.JLabel lbl_1c;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_20c;
    private javax.swing.JLabel lbl_2c;
    private javax.swing.JLabel lbl_50c;
    private javax.swing.JLabel lbl_5c;
    private javax.swing.JLabel lbl_bank_notes;
    private javax.swing.JLabel lbl_coins;
    private javax.swing.JLabel lbl_euro_money_counter;
    private javax.swing.JLabel lbl_total_money;
    private javax.swing.JLabel lbl_€10;
    private javax.swing.JLabel lbl_€100;
    private javax.swing.JLabel lbl_€20;
    private javax.swing.JLabel lbl_€200;
    private javax.swing.JLabel lbl_€5;
    private javax.swing.JLabel lbl_€50;
    private javax.swing.JLabel lbl_€500;
    private javax.swing.JPanel panel_bank_notes;
    private javax.swing.JPanel panel_coins;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_10;
    private javax.swing.JTextField txt_100;
    private javax.swing.JTextField txt_10c;
    private javax.swing.JTextField txt_1c;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_20;
    private javax.swing.JTextField txt_200;
    private javax.swing.JTextField txt_20c;
    private javax.swing.JTextField txt_2c;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_50;
    private javax.swing.JTextField txt_500;
    private javax.swing.JTextField txt_50c;
    private javax.swing.JTextField txt_5c;
    private javax.swing.JTextField txt_bank_notes;
    private javax.swing.JTextField txt_coins;
    private javax.swing.JTextField txt_total_money;
    // End of variables declaration//GEN-END:variables
}
