/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import javax.swing.JOptionPane;

/**
 *
 * @author HermanCosta
 */
public class MoneyCounter extends javax.swing.JFrame {

    String tillClosingDate;
    double totalMoney = 0;
    int input500Qty, input200Qty, input100Qty, input50Qty, input20Qty, input10Qty, input5Qty;
    int input2Qty, input1Qty, input50cQty, input20cQty, input10cQty, input5cQty, input2cQty, input1cQty;
    int countBankNotes, countTotalCoins;

    public MoneyCounter() {
        initComponents();
        setResizable(false);
    }

    public void calcMoneyCounter() {
        double total500 = 500 * input500Qty;
        double total200 = 200 * input200Qty;
        double total100 = 100 * input100Qty;
        double total50 = 50 * input50Qty;
        double total20 = 20 * input20Qty;
        double total10 = 10 * input10Qty;
        double total5 = 5 * input5Qty;

        double total2 = 2 * input2Qty;
        double total1 = 1 * input1Qty;
        double total50c = 0.5 * input50cQty;
        double total20c = 0.2 * input20cQty;
        double total10c = 0.1 * input10cQty;
        double total5c = 0.05 * input5cQty;
        double total2c = 0.02 * input2cQty;
        double total1c = 0.01 * input1cQty;

        totalMoney = total500 + total200 + total100 + total50 + total20 + total10 + total5
                + total2 + total1 + total50c + +total20c + total10c + total5c
                + total2c + total1c;

        totalMoney = Math.round(totalMoney * 100d) / 100d;
        txt_total_money.setText(String.valueOf(totalMoney));

        //count bank notes qty
        countBankNotes = input500Qty + input200Qty + input100Qty + input50Qty + input20Qty + input10Qty + input5Qty;
        txt_total_bank_notes.setText(String.valueOf(countBankNotes));

        //count coins qty
        countTotalCoins = input2Qty + input1Qty + input50cQty + input20cQty + input10cQty + input5cQty + input2cQty + input1cQty;
        txt_total_coins.setText(String.valueOf(countTotalCoins));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_euro_money_counter = new javax.swing.JPanel();
        panel_bank_notes = new javax.swing.JPanel();
        txt_500 = new javax.swing.JTextField();
        txt_200 = new javax.swing.JTextField();
        txt_100 = new javax.swing.JTextField();
        txt_50 = new javax.swing.JTextField();
        txt_10 = new javax.swing.JTextField();
        txt_20 = new javax.swing.JTextField();
        txt_5 = new javax.swing.JTextField();
        lbl_€500 = new javax.swing.JLabel();
        lbl_€200 = new javax.swing.JLabel();
        lbl_€100 = new javax.swing.JLabel();
        lbl_€50 = new javax.swing.JLabel();
        lbl_€20 = new javax.swing.JLabel();
        lbl_€10 = new javax.swing.JLabel();
        lbl_€5 = new javax.swing.JLabel();
        lbl_500_result = new javax.swing.JLabel();
        lbl_200_result = new javax.swing.JLabel();
        lbl_100_result = new javax.swing.JLabel();
        lbl_50_result = new javax.swing.JLabel();
        lbl_20_result = new javax.swing.JLabel();
        lbl_10_result = new javax.swing.JLabel();
        lbl_5_result = new javax.swing.JLabel();
        panel_coins = new javax.swing.JPanel();
        txt_2 = new javax.swing.JTextField();
        txt_1 = new javax.swing.JTextField();
        txt_50c = new javax.swing.JTextField();
        txt_20c = new javax.swing.JTextField();
        txt_10c = new javax.swing.JTextField();
        txt_5c = new javax.swing.JTextField();
        txt_2c = new javax.swing.JTextField();
        txt_1c = new javax.swing.JTextField();
        lbl_2 = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_50c = new javax.swing.JLabel();
        lbl_20c = new javax.swing.JLabel();
        lbl_10c = new javax.swing.JLabel();
        lbl_5c = new javax.swing.JLabel();
        lbl_2c = new javax.swing.JLabel();
        lbl_1c = new javax.swing.JLabel();
        lbl_2_result = new javax.swing.JLabel();
        lbl_1_result = new javax.swing.JLabel();
        lbl_50c_result = new javax.swing.JLabel();
        lbl_20c_result = new javax.swing.JLabel();
        lbl_10c_result = new javax.swing.JLabel();
        lbl_5c_result = new javax.swing.JLabel();
        lbl_2c_result = new javax.swing.JLabel();
        lbl_1c_result = new javax.swing.JLabel();
        txt_total_money = new javax.swing.JTextField();
        txt_total_bank_notes = new javax.swing.JTextField();
        txt_total_coins = new javax.swing.JTextField();
        lbl_total_money = new javax.swing.JLabel();
        lbl_bank_notes = new javax.swing.JLabel();
        lbl_coins = new javax.swing.JLabel();
        btn_copy = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_euro_money_counter.setBackground(new java.awt.Color(204, 204, 204));
        panel_euro_money_counter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EURO Money Counter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 16))); // NOI18N
        panel_euro_money_counter.setMaximumSize(new java.awt.Dimension(690, 360));
        panel_euro_money_counter.setPreferredSize(new java.awt.Dimension(690, 360));
        panel_euro_money_counter.setVerifyInputWhenFocusTarget(false);

        panel_bank_notes.setBackground(new java.awt.Color(204, 204, 204));
        panel_bank_notes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank Notes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 0, 14))); // NOI18N
        panel_bank_notes.setMaximumSize(new java.awt.Dimension(665, 114));
        panel_bank_notes.setPreferredSize(new java.awt.Dimension(0, 0));

        txt_500.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_500ActionPerformed(evt);
            }
        });
        txt_500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_500KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_500KeyReleased(evt);
            }
        });

        txt_200.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_200ActionPerformed(evt);
            }
        });
        txt_200.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_200KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_200KeyReleased(evt);
            }
        });

        txt_100.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_100ActionPerformed(evt);
            }
        });
        txt_100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_100KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_100KeyReleased(evt);
            }
        });

        txt_50.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_50KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_50KeyReleased(evt);
            }
        });

        txt_10.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_10KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_10KeyReleased(evt);
            }
        });

        txt_20.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_20ActionPerformed(evt);
            }
        });
        txt_20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_20KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_20KeyReleased(evt);
            }
        });

        txt_5.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_5KeyReleased(evt);
            }
        });

        lbl_€500.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_€500.setText("€500");

        lbl_€200.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_€200.setText("€200");

        lbl_€100.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_€100.setText("€100");

        lbl_€50.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_€50.setText("€50");

        lbl_€20.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_€20.setText("€20");

        lbl_€10.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_€10.setText("€10");

        lbl_€5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_€5.setText("€5");

        lbl_500_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_500_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_500_result.setText("€500Rst");
        lbl_500_result.setMaximumSize(new java.awt.Dimension(63, 15));
        lbl_500_result.setMinimumSize(new java.awt.Dimension(63, 15));
        lbl_500_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_200_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_200_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_200_result.setText("€200Rst");
        lbl_200_result.setMaximumSize(new java.awt.Dimension(63, 15));
        lbl_200_result.setMinimumSize(new java.awt.Dimension(63, 15));
        lbl_200_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_100_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_100_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_100_result.setText("€100Rst");
        lbl_100_result.setMaximumSize(new java.awt.Dimension(63, 15));
        lbl_100_result.setMinimumSize(new java.awt.Dimension(63, 15));
        lbl_100_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_50_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_50_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_50_result.setText("€50Rst");
        lbl_50_result.setMaximumSize(new java.awt.Dimension(63, 15));
        lbl_50_result.setMinimumSize(new java.awt.Dimension(63, 15));
        lbl_50_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_20_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_20_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_20_result.setText("€20Rst");
        lbl_20_result.setMaximumSize(new java.awt.Dimension(63, 15));
        lbl_20_result.setMinimumSize(new java.awt.Dimension(63, 15));
        lbl_20_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_10_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_10_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_10_result.setText("€10Rst");
        lbl_10_result.setMaximumSize(new java.awt.Dimension(63, 15));
        lbl_10_result.setMinimumSize(new java.awt.Dimension(63, 15));
        lbl_10_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_5_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_5_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_5_result.setText("€5Rst");
        lbl_5_result.setMaximumSize(new java.awt.Dimension(63, 15));
        lbl_5_result.setMinimumSize(new java.awt.Dimension(63, 15));
        lbl_5_result.setPreferredSize(new java.awt.Dimension(0, 15));

        javax.swing.GroupLayout panel_bank_notesLayout = new javax.swing.GroupLayout(panel_bank_notes);
        panel_bank_notes.setLayout(panel_bank_notesLayout);
        panel_bank_notesLayout.setHorizontalGroup(
            panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_500, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_500_result, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_200_result, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_200, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_100, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_100_result, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_50, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_50_result, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lbl_20_result, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bank_notesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_10_result, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_5_result, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbl_€500)
                        .addGap(51, 51, 51)
                        .addComponent(lbl_€200)
                        .addGap(53, 53, 53)
                        .addComponent(lbl_€100)
                        .addGap(56, 56, 56)
                        .addComponent(lbl_€50)
                        .addGap(59, 59, 59)
                        .addComponent(lbl_€20)
                        .addGap(57, 57, 57)
                        .addComponent(lbl_€10)
                        .addGap(68, 68, 68)
                        .addComponent(lbl_€5)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panel_bank_notesLayout.setVerticalGroup(
            panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bank_notesLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_€500)
                            .addComponent(lbl_€200))
                        .addGap(30, 30, 30))
                    .addGroup(panel_bank_notesLayout.createSequentialGroup()
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_€100)
                            .addComponent(lbl_€50)
                            .addComponent(lbl_€20)
                            .addComponent(lbl_€10)
                            .addComponent(lbl_€5))
                        .addGap(1, 1, 1)
                        .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_200, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_500, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_100, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(panel_bank_notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_500_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_200_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_100_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_50_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_20_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_10_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_5_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_coins.setBackground(new java.awt.Color(204, 204, 204));
        panel_coins.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank Notes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 0, 14))); // NOI18N
        panel_coins.setMaximumSize(new java.awt.Dimension(665, 114));
        panel_coins.setPreferredSize(new java.awt.Dimension(0, 0));

        txt_2.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_2ActionPerformed(evt);
            }
        });
        txt_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_2KeyReleased(evt);
            }
        });

        txt_1.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1ActionPerformed(evt);
            }
        });
        txt_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_1KeyReleased(evt);
            }
        });

        txt_50c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_50c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_50cActionPerformed(evt);
            }
        });
        txt_50c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_50cKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_50cKeyReleased(evt);
            }
        });

        txt_20c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_20c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_20cActionPerformed(evt);
            }
        });
        txt_20c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_20cKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_20cKeyReleased(evt);
            }
        });

        txt_10c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_10c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_10cKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_10cKeyReleased(evt);
            }
        });

        txt_5c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_5c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_5cKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_5cKeyReleased(evt);
            }
        });

        txt_2c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_2c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_2cKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_2cKeyReleased(evt);
            }
        });

        txt_1c.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_1c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1cActionPerformed(evt);
            }
        });
        txt_1c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_1cKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_1cKeyReleased(evt);
            }
        });

        lbl_2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_2.setText("€2");

        lbl_1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_1.setText("€1");

        lbl_50c.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_50c.setText("50c");

        lbl_20c.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_20c.setText("20c");

        lbl_10c.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_10c.setText("10c");

        lbl_5c.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_5c.setText("5c");

        lbl_2c.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_2c.setText("2c");

        lbl_1c.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_1c.setText("1c");

        lbl_2_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_2_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_2_result.setText("€2Rst");
        lbl_2_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_2_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_2_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_1_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_1_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_1_result.setText("€1Rst");
        lbl_1_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_1_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_1_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_50c_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_50c_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_50c_result.setText("50cRst");
        lbl_50c_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_50c_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_50c_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_20c_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_20c_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_20c_result.setText("20cRst");
        lbl_20c_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_20c_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_20c_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_10c_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_10c_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_10c_result.setText("10cRst");
        lbl_10c_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_10c_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_10c_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_5c_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_5c_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_5c_result.setText("5cRst");
        lbl_5c_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_5c_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_5c_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_2c_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_2c_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_2c_result.setText("2cRst");
        lbl_2c_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_2c_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_2c_result.setPreferredSize(new java.awt.Dimension(0, 15));

        lbl_1c_result.setBackground(new java.awt.Color(204, 204, 204));
        lbl_1c_result.setForeground(new java.awt.Color(204, 204, 204));
        lbl_1c_result.setText("1cRst");
        lbl_1c_result.setMaximumSize(new java.awt.Dimension(57, 15));
        lbl_1c_result.setMinimumSize(new java.awt.Dimension(57, 15));
        lbl_1c_result.setPreferredSize(new java.awt.Dimension(0, 15));

        javax.swing.GroupLayout panel_coinsLayout = new javax.swing.GroupLayout(panel_coins);
        panel_coins.setLayout(panel_coinsLayout);
        panel_coinsLayout.setHorizontalGroup(
            panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_coinsLayout.createSequentialGroup()
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_2)
                        .addGap(64, 64, 64)
                        .addComponent(lbl_1))
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_2_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_1_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_50c_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_50c, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbl_50c)))
                .addGap(19, 19, 19)
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_20c_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_20c, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                        .addComponent(lbl_20c)
                        .addGap(39, 39, 39)))
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_10c_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_10c, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                        .addComponent(lbl_10c)
                        .addGap(35, 35, 35)))
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_5c_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_5c, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbl_5c)))
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_2c, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_2c_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_1c, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_1c_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_coinsLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbl_2c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_1c)
                        .addGap(27, 27, 27))))
        );
        panel_coinsLayout.setVerticalGroup(
            panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coinsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_coinsLayout.createSequentialGroup()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_10c)
                                    .addComponent(lbl_20c)
                                    .addComponent(lbl_50c)
                                    .addComponent(lbl_1))
                                .addGap(0, 0, 0)
                                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_10c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_20c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addComponent(lbl_2)
                                .addGap(0, 0, 0)
                                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_50c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0)
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_50c_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_20c_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_10c_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_2c_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_1c_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_coinsLayout.createSequentialGroup()
                        .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_5c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_2c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_1c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_coinsLayout.createSequentialGroup()
                                .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_5c)
                                    .addComponent(lbl_2c)
                                    .addComponent(lbl_1c))
                                .addGap(30, 30, 30)))
                        .addGap(0, 0, 0)
                        .addComponent(lbl_5c_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_1_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_2_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        txt_total_money.setEditable(false);
        txt_total_money.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_total_money.setFocusable(false);

        txt_total_bank_notes.setEditable(false);
        txt_total_bank_notes.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_total_bank_notes.setFocusable(false);
        txt_total_bank_notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_bank_notesActionPerformed(evt);
            }
        });

        txt_total_coins.setEditable(false);
        txt_total_coins.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        txt_total_coins.setFocusable(false);
        txt_total_coins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_coinsActionPerformed(evt);
            }
        });

        lbl_total_money.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_total_money.setText("Total Money €");

        lbl_bank_notes.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_bank_notes.setText("Bank notes");

        lbl_coins.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl_coins.setText("Coins");

        btn_copy.setBackground(new java.awt.Color(0, 0, 0));
        btn_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_copy.png"))); // NOI18N
        btn_copy.setToolTipText("Copy to total money to clipboard");
        btn_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copyActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 0, 0));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_erase.png"))); // NOI18N
        btn_clear.setToolTipText("Clear fields");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_euro_money_counterLayout = new javax.swing.GroupLayout(panel_euro_money_counter);
        panel_euro_money_counter.setLayout(panel_euro_money_counterLayout);
        panel_euro_money_counterLayout.setHorizontalGroup(
            panel_euro_money_counterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_euro_money_counterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_total_money)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_total_money, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_bank_notes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_total_bank_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_coins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_total_coins, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panel_coins, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_bank_notes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_euro_money_counterLayout.setVerticalGroup(
            panel_euro_money_counterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_euro_money_counterLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel_bank_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_coins, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_euro_money_counterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_euro_money_counterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_total_money, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_total_money)
                        .addComponent(txt_total_bank_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_bank_notes)
                        .addComponent(txt_total_coins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_coins))
                    .addComponent(btn_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(panel_euro_money_counter, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_200ActionPerformed

    private void txt_total_coinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_coinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_coinsActionPerformed

    private void btn_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copyActionPerformed
        // TODO add your handling code here:
        StringSelection stringSelection = new StringSelection(txt_total_money.getText());
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null);
        JOptionPane.showMessageDialog(this, txt_total_money.getText() + " Copied to Clipboard");
    }//GEN-LAST:event_btn_copyActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_500.setText("");
        txt_200.setText("");
        txt_100.setText("");
        txt_50.setText("");
        txt_10.setText("");
        txt_20.setText("");
        txt_5.setText("");
        txt_2.setText("");
        txt_1.setText("");
        txt_50c.setText("");
        txt_20c.setText("");
        txt_10c.setText("");
        txt_5c.setText("");
        txt_2c.setText("");
        txt_1c.setText("");
        txt_total_money.setText("");
        txt_total_bank_notes.setText("");
        txt_total_coins.setText("");

        input500Qty = 0;
        input200Qty = 0;
        input100Qty = 0;
        input50Qty = 0;
        input20Qty = 0;
        input10Qty = 0;
        input5Qty = 0;
        input2Qty = 0;
        input1Qty = 0;
        input50cQty = 0;
        input20cQty = 0;
        input10cQty = 0;
        input5cQty = 0;
        input2cQty = 0;
        input1cQty = 0;
        totalMoney = 0;
        countBankNotes = 0;
        countTotalCoins = 0;

        lbl_500_result.setForeground(new Color(204, 204, 204));
        lbl_200_result.setForeground(new Color(204, 204, 204));
        lbl_100_result.setForeground(new Color(204, 204, 204));
        lbl_50_result.setForeground(new Color(204, 204, 204));
        lbl_20_result.setForeground(new Color(204, 204, 204));
        lbl_10_result.setForeground(new Color(204, 204, 204));
        lbl_5_result.setForeground(new Color(204, 204, 204));
        lbl_2_result.setForeground(new Color(204, 204, 204));
        lbl_1_result.setForeground(new Color(204, 204, 204));
        lbl_50c_result.setForeground(new Color(204, 204, 204));
        lbl_20c_result.setForeground(new Color(204, 204, 204));
        lbl_10c_result.setForeground(new Color(204, 204, 204));
        lbl_5c_result.setForeground(new Color(204, 204, 204));
        lbl_2c_result.setForeground(new Color(204, 204, 204));
        lbl_1c_result.setForeground(new Color(204, 204, 204));

        txt_500.requestFocus();

    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_total_bank_notesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_bank_notesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_total_bank_notesActionPerformed

    private void txt_500KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_500KeyReleased
        // TODO add your handling code here:
        if (txt_500.getText().trim().isEmpty()) {
            input500Qty = 0;
            lbl_500_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input500Qty = Integer.parseInt(txt_500.getText());
            lbl_500_result.setText(String.valueOf(500 * input500Qty));
            lbl_500_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_500KeyReleased

    private void txt_200KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_200KeyReleased
        // TODO add your handling code here:
        if (txt_200.getText().trim().isEmpty()) {
            input200Qty = 0;
            lbl_200_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input200Qty = Integer.parseInt(txt_200.getText());
            lbl_200_result.setText(String.valueOf(200 * input200Qty));
            lbl_200_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_200KeyReleased

    private void txt_100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_100KeyReleased
        // TODO add your handling code here:
        if (txt_100.getText().trim().isEmpty()) {
            input100Qty = 0;
            lbl_100_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input100Qty = Integer.parseInt(txt_100.getText());
            lbl_100_result.setText(String.valueOf(100 * input100Qty));
            lbl_100_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_100KeyReleased

    private void txt_50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_50KeyReleased
        // TODO add your handling code here:
        if (txt_50.getText().trim().isEmpty()) {
            input50Qty = 0;
            lbl_50_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input50Qty = Integer.parseInt(txt_50.getText());
            lbl_50_result.setText(String.valueOf(50 * input50Qty));
            lbl_50_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_50KeyReleased

    private void txt_10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_10KeyReleased
        // TODO add your handling code here:
        if (txt_10.getText().trim().isEmpty()) {
            input10Qty = 0;
            lbl_10_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input10Qty = Integer.parseInt(txt_10.getText());
            lbl_10_result.setText(String.valueOf(10 * input10Qty));
            lbl_10_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_10KeyReleased

    private void txt_20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_20KeyReleased
        // TODO add your handling code here:
        if (txt_20.getText().trim().isEmpty()) {

            input20Qty = 0;
            lbl_20_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input20Qty = Integer.parseInt(txt_20.getText());
            lbl_20_result.setText(String.valueOf(20 * input20Qty));
            lbl_20_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_20KeyReleased

    private void txt_5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_5KeyReleased
        // TODO add your handling code here:
        if (txt_5.getText().trim().isEmpty()) {
            input5Qty = 0;
            lbl_5_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input5Qty = Integer.parseInt(txt_5.getText());
            lbl_5_result.setText(String.valueOf(5 * input5Qty));
            lbl_5_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_5KeyReleased

    private void txt_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2KeyReleased
        // TODO add your handling code here:
        if (txt_2.getText().trim().isEmpty()) {
            input2Qty = 0;
            lbl_2_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input2Qty = Integer.parseInt(txt_2.getText());
            lbl_2_result.setText(String.valueOf(2 * input2Qty));
            lbl_2_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_2KeyReleased

    private void txt_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1KeyReleased
        // TODO add your handling code here:
        if (txt_1.getText().trim().isEmpty()) {
            input1Qty = 0;
            lbl_1_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input1Qty = Integer.parseInt(txt_1.getText());
            lbl_1_result.setText(String.valueOf(1 * input1Qty));
            lbl_1_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_1KeyReleased

    private void txt_50cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_50cKeyReleased
        // TODO add your handling code here:
        if (txt_50c.getText().trim().isEmpty()) {
            input50cQty = 0;
            lbl_50c_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input50cQty = Integer.parseInt(txt_50c.getText());
            lbl_50c_result.setText(String.valueOf(Math.floor(0.50 * input50cQty * 100) / 100));
            lbl_50c_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_50cKeyReleased

    private void txt_20cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_20cKeyReleased
        // TODO add your handling code here:
        if (txt_20c.getText().trim().isEmpty()) {
            input20cQty = 0;
            lbl_20c_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input20cQty = Integer.parseInt(txt_20c.getText());
            lbl_20c_result.setText(String.valueOf(Math.floor(0.20 * input20cQty * 100) / 100));
            lbl_20c_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_20cKeyReleased

    private void txt_10cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_10cKeyReleased
        // TODO add your handling code here:
        if (txt_10c.getText().trim().isEmpty()) {
            input10cQty = 0;
            lbl_10c_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input10cQty = Integer.parseInt(txt_10c.getText());
            lbl_10c_result.setText(String.valueOf(Math.floor(0.10 * input10cQty * 100) / 100));
            lbl_10c_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_10cKeyReleased

    private void txt_5cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_5cKeyReleased
        // TODO add your handling code here:
        if (txt_5c.getText().trim().isEmpty()) {
            input5cQty = 0;
            lbl_5c_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input5cQty = Integer.parseInt(txt_5c.getText());
            lbl_5c_result.setText(String.valueOf(Math.floor(0.05 * input5cQty * 100) / 100));
            lbl_5c_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_5cKeyReleased

    private void txt_2cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2cKeyReleased
        // TODO add your handling code here:
        if (txt_2c.getText().trim().isEmpty()) {
            input2cQty = 0;
            lbl_2c_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input2cQty = Integer.parseInt(txt_2c.getText());
            lbl_2c_result.setText(String.valueOf(Math.floor(0.02 * input2cQty * 100) / 100));
            lbl_2c_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_2cKeyReleased

    private void txt_1cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1cKeyReleased
        // TODO add your handling code here:
        if (txt_1c.getText().trim().isEmpty()) {
            input1cQty = 0;
            lbl_1c_result.setForeground(new Color(204, 204, 204));
            calcMoneyCounter();
        } else {
            input1cQty = Integer.parseInt(txt_1c.getText());
            lbl_1c_result.setText(String.valueOf(Math.floor(0.01 * input1cQty * 100) / 100));
            lbl_1c_result.setForeground(Color.black);
            calcMoneyCounter();
        }
    }//GEN-LAST:event_txt_1cKeyReleased

    private void txt_20cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_20cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_20cActionPerformed

    private void txt_500KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_500KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_500.setEditable(false);
        } else {
            txt_500.setEditable(true);
        }
    }//GEN-LAST:event_txt_500KeyPressed

    private void txt_200KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_200KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_200.setEditable(false);
        } else {
            txt_200.setEditable(true);
        }
    }//GEN-LAST:event_txt_200KeyPressed

    private void txt_100KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_100KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_100.setEditable(false);
        } else {
            txt_100.setEditable(true);
        }
    }//GEN-LAST:event_txt_100KeyPressed

    private void txt_50KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_50KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_50.setEditable(false);
        } else {
            txt_50.setEditable(true);
        }
    }//GEN-LAST:event_txt_50KeyPressed

    private void txt_10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_10KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_10.setEditable(false);
        } else {
            txt_10.setEditable(true);
        }
    }//GEN-LAST:event_txt_10KeyPressed

    private void txt_20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_20KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_20.setEditable(false);
        } else {
            txt_20.setEditable(true);
        }
    }//GEN-LAST:event_txt_20KeyPressed

    private void txt_5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_5KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_5.setEditable(false);
        } else {
            txt_5.setEditable(true);
        }
    }//GEN-LAST:event_txt_5KeyPressed

    private void txt_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_2.setEditable(false);
        } else {
            txt_2.setEditable(true);
        }
    }//GEN-LAST:event_txt_2KeyPressed

    private void txt_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1KeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_1.setEditable(false);
        } else {
            txt_1.setEditable(true);
        }
    }//GEN-LAST:event_txt_1KeyPressed

    private void txt_20cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_20cKeyPressed
        // TODO add your handling code here:
        //Accepts number characters only
        if (Character.isLetter(evt.getKeyChar())) {
            txt_20c.setEditable(false);
        } else {
            txt_20c.setEditable(true);
        }
    }//GEN-LAST:event_txt_20cKeyPressed

    private void txt_50cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_50cKeyPressed
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            txt_50c.setEditable(false);
        } else {
            txt_50c.setEditable(true);
        }
    }//GEN-LAST:event_txt_50cKeyPressed

    private void txt_10cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_10cKeyPressed
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            txt_10c.setEditable(false);
        } else {
            txt_10c.setEditable(true);
        }
    }//GEN-LAST:event_txt_10cKeyPressed

    private void txt_5cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_5cKeyPressed
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            txt_5c.setEditable(false);
        } else {
            txt_5c.setEditable(true);
        }
    }//GEN-LAST:event_txt_5cKeyPressed

    private void txt_2cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2cKeyPressed
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            txt_2c.setEditable(false);
        } else {
            txt_2c.setEditable(true);
        }
    }//GEN-LAST:event_txt_2cKeyPressed

    private void txt_1cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1cKeyPressed
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            txt_1c.setEditable(false);
        } else {
            txt_1c.setEditable(true);
        }
    }//GEN-LAST:event_txt_1cKeyPressed

    private void txt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_2ActionPerformed

    private void txt_500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_500ActionPerformed

    private void txt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1ActionPerformed

    private void txt_50cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_50cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_50cActionPerformed

    private void txt_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_20ActionPerformed

    private void txt_100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_100ActionPerformed

    private void txt_1cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1cActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_copy;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_100_result;
    private javax.swing.JLabel lbl_10_result;
    private javax.swing.JLabel lbl_10c;
    private javax.swing.JLabel lbl_10c_result;
    private javax.swing.JLabel lbl_1_result;
    private javax.swing.JLabel lbl_1c;
    private javax.swing.JLabel lbl_1c_result;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_200_result;
    private javax.swing.JLabel lbl_20_result;
    private javax.swing.JLabel lbl_20c;
    private javax.swing.JLabel lbl_20c_result;
    private javax.swing.JLabel lbl_2_result;
    private javax.swing.JLabel lbl_2c;
    private javax.swing.JLabel lbl_2c_result;
    private javax.swing.JLabel lbl_500_result;
    private javax.swing.JLabel lbl_50_result;
    private javax.swing.JLabel lbl_50c;
    private javax.swing.JLabel lbl_50c_result;
    private javax.swing.JLabel lbl_5_result;
    private javax.swing.JLabel lbl_5c;
    private javax.swing.JLabel lbl_5c_result;
    private javax.swing.JLabel lbl_bank_notes;
    private javax.swing.JLabel lbl_coins;
    private javax.swing.JLabel lbl_total_money;
    private javax.swing.JLabel lbl_€10;
    private javax.swing.JLabel lbl_€100;
    private javax.swing.JLabel lbl_€20;
    private javax.swing.JLabel lbl_€200;
    private javax.swing.JLabel lbl_€5;
    private javax.swing.JLabel lbl_€50;
    private javax.swing.JLabel lbl_€500;
    private javax.swing.JPanel panel_bank_notes;
    private javax.swing.JPanel panel_coins;
    private javax.swing.JPanel panel_euro_money_counter;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_10;
    private javax.swing.JTextField txt_100;
    private javax.swing.JTextField txt_10c;
    private javax.swing.JTextField txt_1c;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_20;
    private javax.swing.JTextField txt_200;
    private javax.swing.JTextField txt_20c;
    private javax.swing.JTextField txt_2c;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_50;
    private javax.swing.JTextField txt_500;
    private javax.swing.JTextField txt_50c;
    private javax.swing.JTextField txt_5c;
    private javax.swing.JTextField txt_total_bank_notes;
    private javax.swing.JTextField txt_total_coins;
    private javax.swing.JTextField txt_total_money;
    // End of variables declaration//GEN-END:variables
}
