/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextPane;

/**
 *
 * @author user
 */
public class PrintOrder extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public PrintOrder() {
        initComponents();
    }
    
    String _orderNo;
    String _firstName;
    String _lastName;
    String _contact;
    String _email;
    String _deviceBrand;
    String _deviceModel;
    String _serialNumber;
    String _fault;
    String _importantNotes;
    String _serviceProduct;
    String _price;
    String _deposit;
    String _due;
    
    PrintOrder(String orderNo, String firstName, String lastName, String contact, String email, String deviceBrand,
               String deviceModel, String serialNumber, String fault, String importantNotes, String serviceProduct,
               String price, String deposit, String due) {
        
    
        initComponents();
        
        this._orderNo = orderNo;
        this._firstName = firstName;
        this._lastName = lastName;
        this._contact = contact;
        this._email = email;
        this._deviceBrand = deviceBrand;
        this._deviceModel = deviceModel;
        this._serialNumber = serialNumber;
        this._importantNotes = importantNotes;
        this._serviceProduct = serviceProduct;
        this._price = price;
        this._deposit = deposit;
        this._due = due;
        
        txt_panel_print.setText(txt_panel_print.getText() + "**********************************************\n");
        txt_panel_print.setText(txt_panel_print.getText() + "******************PCHOUSE*********************\n");
        txt_panel_print.setText(txt_panel_print.getText() + "\n");
        
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Order No: " + _orderNo +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Customer Name: " + _firstName + " " + _lastName + "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Contact No: " + _contact +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Email Address: " + _email +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Brand: " + _deviceBrand +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Model: " + _deviceModel +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "S/N: " + _serialNumber +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Important Notes: " + _importantNotes +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Service|Product: " + _serviceProduct +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Price: €" + _price +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Deposit Paid: €" + _deposit +  "\n");
        txt_panel_print.setText(txt_panel_print.getText() + " " + "Due: €" + _due +  "\n");
        
        txt_panel_print.setText(txt_panel_print.getText() + "**********************************************\n");
        txt_panel_print.setText(txt_panel_print.getText() + "**********************************************\n");
        txt_panel_print.setText(txt_panel_print.getText() + "********Thank you for trusting us*************\n");
        
        
        //about header ans footer
        //MessageFormat footer = new MessageFormat("Page - {0}");
        
        
        
        
        //printOrderDetails(txt_panel_print);
        
        
//        try {
//            txPrintPanel.print();
//        } catch (PrinterException ex) {
//            Logger.getLogger(PrintOrder.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
    

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_panel_print = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txt_panel_print.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jScrollPane1.setViewportView(txt_panel_print);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txt_panel_print;
    // End of variables declaration//GEN-END:variables
    
    private void printOrderDetails(JTextPane panel)
    {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Order Details");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                
                if(pageIndex > 0)
                {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D = (Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX() * 2, pageFormat.getImageableY() * 2);
                graphics2D.scale(0.5, 0.5);
                
              
                
              txt_panel_print.paint(graphics2D);
              return Printable.PAGE_EXISTS;
            }
        });
        
        boolean returningResult = printerJob.printDialog();
        
        //MessageFormat footer = new MessageFormat("Page - {0}");
        
        if(returningResult)
        {
            try {
                printerJob.print();

            } catch (PrinterException ex) {
                Logger.getLogger(PrintOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }


}
