/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class PrintOrder extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public PrintOrder() {
        initComponents();
    }
    
    String _orderNo;
    String _firstName;
    String _lastName;
    String _contact;
    String _email;
    String _deviceBrand;
    String _deviceModel;
    String _serialNumber;
    String _fault;
    String _importantNotes;
    String _serviceProduct;
    String _price;
    String _deposit;
    String _due;
    
    
    //new PrintOrder(orderNo,firstName,lastName,contact,email,deviceBrand,deviceModel,serialNumber,
    //fault,importantNotes,serviceProduct,price,deposit,due).setVisible(true);
    
    
   PrintOrder(String orderNo, String firstName, String lastName, String contact, String email, String deviceBrand,
              String deviceModel, String serialNumber, String fault, String importantNotes, String serviceProduct,
              String price, String deposit, String due) {
        
    
        initComponents();
        
        this._orderNo = orderNo;
        this._firstName = firstName;
        this._lastName = lastName;
        this._contact = contact;
        this._email = email;
        this._deviceBrand = deviceBrand;
        this._deviceModel = deviceModel;
        this._serialNumber = serialNumber;
        this._importantNotes = importantNotes;
        this._serviceProduct = serviceProduct;
        this._price = price;
        this._deposit = deposit;
        this._due = due;
        
        txPrintPanel.setText(txPrintPanel.getText() + "**********************************************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "******************PCHOUSE*********************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "\n");
        
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Order No: " + _orderNo +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Customer Name: " + _firstName + " " + _lastName + "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Contact No: " + _contact +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Email Address: " + _email +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Brand: " + _deviceBrand +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Model: " + _deviceModel +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "S/N: " + _serialNumber +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Important Notes: " + _importantNotes +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Service|Product: " + _serviceProduct +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Price: €" + _price +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Deposit Paid: €" + _deposit +  "\n");
        txPrintPanel.setText(txPrintPanel.getText() + " " + "Due: €" + _due +  "\n");
        
        txPrintPanel.setText(txPrintPanel.getText() + "**********************************************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "**********************************************\n");
        txPrintPanel.setText(txPrintPanel.getText() + "********Thank you for trusting us*************\n");
        
        try {
            txPrintPanel.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PrintOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txPrintPanel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txPrintPanel.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jScrollPane1.setViewportView(txPrintPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txPrintPanel;
    // End of variables declaration//GEN-END:variables
}
